'use client';
import { ArrowDownRight, ArrowRight, Menu, Phone, X } from 'lucide-react';
import { useState } from 'react';

const areas=[['01','Brottmål','Offentlig och privat försvarare, målsägandebiträde samt särskild företrädare för barn.'],['02','Familjerätt','Vårdnad, barns boende, umgänge, faderskap, verkställighet och vårdnadsöverflytt.'],['03','Socialrätt','Juridiskt stöd i mål enligt LVU, LVM, LPT, LRV och LBSB.'],['04','Migrationsrätt','Rådgivning och biträde i frågor om asyl, förvar, arbetstillstånd, anknytning och medborgarskap.']];
const people=[['EDIBA GERGES','Advokat','070-454 70 99','ediba@advocatum.se','https://www.advocatum.se/wp-content/uploads/2024/09/IMG_7026.jpg'],['HELEN SULIMAN','Biträdande jurist','073-746 32 53','helen@advocatum.se','https://www.advocatum.se/wp-content/uploads/2024/09/Photoroom_20240901_221527.jpg'],['MARKUS MADOSON','Biträdande jurist','073-739 29 19','markus@advocatum.se','https://www.advocatum.se/wp-content/uploads/2026/06/DSC08959-Redigera-e1781555623357.jpg']];
export default function Home(){const[open,setOpen]=useState(false);return <main>
<header><a className="logo" href="#top">ADVOCATUM<span>ADVOKATBYRÅ</span></a><nav className={open?'open':''}><a href="#om">Om oss</a><a href="#omraden">Verksamhetsområden</a><a href="#team">Medarbetare</a><a href="#kontakt">Kontakt</a><a className="phone" href="tel:+46105164440"><Phone size={15}/>010-516 44 40</a></nav><button className="menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></header>
<section className="hero" id="top"><video autoPlay muted loop playsInline poster="https://www.advocatum.se/wp-content/uploads/2024/09/IMG_7026.jpg"><source media="(max-width: 560px)" src="https://www.advocatum.se/wp-content/uploads/2024/07/E2E74B5F-1A6E-40D7-89FB-5EAD3051A643.mp4" type="video/mp4"/><source src="https://www.advocatum.se/wp-content/uploads/2024/07/copy_14418A3E-ACE3-4361-B2A8-8F324165B0F5.mp4" type="video/mp4"/></video><div className="shade"/><a className="btn gold hero-button" href="#kontakt">Kontakta oss <ArrowRight size={17}/></a><div className="hero-side"><span>SV</span><span>EN</span><span>AR</span><span>SYR</span></div></section>
<section className="hero-message"><p className="kicker">Humanjuridik · hela Sverige</p><h1>Rätt ombud.<br/><em>När det betyder som mest.</em></h1><div><p>Gedigen erfarenhet och kvalificerad juridisk kompetens inom brottmål, familjerätt, socialrätt och migrationsrätt.</p><div className="actions"><a className="btn dark" href="tel:+46105164440"><Phone size={17}/> Ring oss</a><a className="text-link" href="#om">Lär känna Advocatum <ArrowDownRight size={17}/></a></div></div></section>
<section className="trust"><span>Humanjuridisk expertis</span><span>Uppdrag i hela Sverige</span><span>Svenska · Engelska · Arabiska · Syrianska</span></section>
<section className="about" id="om"><div className="label">Om Advocatum</div><div><h2>Juridisk skärpa.<br/><i>Mänskligt engagemang.</i></h2><div className="cols"><p>Advocatum är en humanjuridisk advokatbyrå. Vårt team av erfarna jurister engagerar sig helhjärtat i varje ärende och arbetar för bästa möjliga resultat för våra klienter.</p><p>Du har i regel rätt att själv välja den advokat eller jurist som ska företräda dig genom hela rättsprocessen. Vi tar uppdrag över hela Sverige och erbjuder rådgivning på svenska, engelska, arabiska och syrianska.</p></div></div></section>
<section className="choose"><div className="choose-number">A—01</div><div><p className="label">Välj rätt ombud</p><h2>En trygg relation genom hela rättsprocessen.</h2><p>Du har i regel rätt att välja den advokat eller jurist som du önskar ska företräda dig. Därför är det viktigt att välja ett ombud som både förstår juridiken och tar sig tid att förstå dig.</p></div><div className="choose-aside"><strong>Fyra språk.<br/>Ett personligt bemötande.</strong><p>Svenska<br/>Engelska<br/>Arabiska<br/>Syrianska</p></div></section>
<section className="areas" id="omraden"><div className="areas-head"><p className="label light">Verksamhetsområden</p><h2>Vi står vid din sida.</h2></div><div className="area-list">{areas.map(a=><article key={a[0]}><span>{a[0]}</span><h3>{a[1]}</h3><p>{a[2]}</p><ArrowDownRight/></article>)}</div></section>
<section className="statement"><p>Vårt åtagande sträcker sig över hela Sverige.</p><h2>Rätt stöd ska inte<br/>bero på var du bor.</h2></section>
<section className="path"><div><p className="label">Vägen framåt</p><h2>Vi gör processen tydligare.</h2></div><ol><li><span>01</span><div><strong>Första kontakten</strong><p>Berätta kort vad som har hänt och vad du behöver hjälp med.</p></div></li><li><span>02</span><div><strong>Vi går igenom ärendet</strong><p>Vi bedömer situationen, förklarar alternativen och svarar på dina frågor.</p></div></li><li><span>03</span><div><strong>Ditt ombud genom processen</strong><p>Du får juridiskt stöd och en tydlig kontakt hela vägen framåt.</p></div></li></ol></section>
<section className="team" id="team"><div className="team-head"><p className="label">Vi på byrån</p><h2>Erfarenhet som gör skillnad.</h2></div><div className="people">{people.map((p,i)=><article key={p[0]}><div className="portrait"><img src={p[4]} alt={p[0]}/><span>0{i+1}</span></div><h3>{p[0]}</h3><p>{p[1]}</p><a href={'tel:'+p[2].replaceAll(' ','')}>{p[2]}</a><a href={'mailto:'+p[3]}>{p[3]}</a></article>)}</div></section>
<section className="finance"><div><p className="label light">Finansiering</p><h2>Vi hjälper dig förstå dina möjligheter.</h2></div><p>Som privatperson kan du i många fall få delar av ombudskostnaden finansierad genom rättsskydd i hemförsäkringen eller genom statlig rättshjälp. Vi hjälper dig med ansökan och går igenom vad som gäller i just ditt ärende.</p></section>
<section className="contact" id="kontakt"><p className="label light">Ta första steget</p><div><h2>Berätta vad som har hänt.</h2><aside><p>Du behöver inte veta exakt vilken hjälp du behöver. Kontakta oss så går vi igenom nästa steg tillsammans.</p><a className="btn gold" href="tel:+46105164440"><Phone size={17}/>010-516 44 40</a><a href="mailto:info@advocatum.se">info@advocatum.se</a></aside></div></section>
<footer><a className="logo invert" href="#top">ADVOCATUM<span>ADVOKATBYRÅ</span></a><div><small>Besöksadress</small><p>Veddestabron 14<br/>177 45 Järfälla</p></div><div><small>Postadress</small><p>Veddestabron 10<br/>177 48 Järfälla</p></div><div><small>Öppettider</small><p>Måndag–fredag<br/>08:00–17:00</p></div><div><small>Bolagsuppgifter</small><p>Org.nr 559284-2644<br/>Bankgiro 5588-0876</p></div><p className="copy">© 2026 Advokatbyrån Advocatum AB</p></footer>
</main>}
